# Generated by Django 4.1.1 on 2022-09-29 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_musician_alter_cars_options_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='feat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feats', to='main.musician'),
        ),
    ]
