# Generated by Django 4.1.1 on 2022-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_song_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
