# Generated by Django 4.1.1 on 2022-09-29 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_song_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(['mp3'], message='file must be mp3')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.FileField(blank=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4'], message='file must be mp4')]),
        ),
    ]
