# Generated by Django 4.1.1 on 2022-09-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_audio_alter_song_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
